config:
  experiment_name: "painting_0004"
  # init_img: "/grogu/user/amahapat/dreambooth/Eulerian/validation_warping_imgs/00990_00000_gt/000.png"
  # init_img: "/grogu/user/amahapat/dreambooth/Eulerian/eulerian_data/train/00561_00334_input.jpg"
  init_img: "./data/painting_0004.png"
  ddim_steps: 999 # we use 999 steps for the best reconstruction
  save_feature_timesteps: 50
  # prompt: ''